StylesPath = .vale/styles
MinAlertLevel = warning

[*.{md,mdx}]
BasedOnStyles = Sessionboard

# Don't lint imports/JSX blocks or code
TokenIgnores = (import \{[^}]+\} from '[^']+';)
BlockIgnores = (?s)```.*?```
