#!/usr/bin/env python3
"""Repoint links that still address the HubSpot knowledge base.

Pages rebuilt from the archive come back with the links their authors wrote in
HubSpot: /en/knowledge-base/<slug> for other articles, and #CamelCase jump
anchors for their own headings. Neither resolves here — the slugs live behind a
redirect and the anchors were generated by HubSpot's renderer, so Starlight's
link validator rejects all of them.

Article links are remapped through redirects-301.csv. Jump-link lists are
deleted: Starlight renders a table of contents from the headings already.

    python3 scripts/fix_legacy_links.py --dry-run
    python3 scripts/fix_legacy_links.py --apply
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / 'src/content/docs'

LEGACY = re.compile(
    r'\]\((?:https?://(?:learn|help)\.sessionboard\.com)?(/en/knowledge-base/[^)#\s]+)'
    r'(#[^)\s]*)?\)'
)
# A jump-link list arrives as bullets, as a numbered list, or as bare links in
# their own paragraphs, usually under an "In this article" label. Blank lines
# may separate the entries, because HubSpot's editor double-spaced them.
TOC_ENTRY = r'(?:[-*]\s+|\d+\.\s+)?\[[^\]]+\]\(#[^)]*\)'
TOC_BLOCK = re.compile(
    rf'(?:^[ \t]*(?:in this article|contents|table of contents)[ \t]*\n(?:[ \t]*\n)?)?'
    rf'(?:^[ \t]*{TOC_ENTRY}[ \t]*\n(?:[ \t]*\n)?){{2,}}',
    re.M | re.I,
)


def redirect_map() -> dict[str, str]:
    out = {}
    for r in csv.DictReader(open(ROOT / 'redirects-301.csv')):
        path = re.sub(r'^https?://[^/]+', '', r['old_url']).rstrip('/')
        out[path] = r['new_path']
    return out


def drop_toc(m: re.Match) -> str:
    items = [l for l in m.group(0).strip().split('\n') if l.strip()]
    anchors = sum(1 for i in items if re.search(r'\]\(#', i))
    return '' if anchors >= 2 and anchors / len(items) >= 0.6 else m.group(0)


def main() -> None:
    apply = '--apply' in sys.argv
    redirects = redirect_map()
    relinked = tocs = files = unmapped = 0

    for path in sorted(DOCS.rglob('*.mdx')):
        original = path.read_text()

        def swap(m: re.Match) -> str:
            nonlocal unmapped
            # HubSpot appended ?hsLang=en to links copied out of its editor.
            slug = m.group(1).split('?')[0].rstrip('/')
            target = redirects.get(slug)
            if not target:
                unmapped += 1
                print(f'  UNMAPPED {path.relative_to(DOCS)}: {m.group(1)}')
                return m.group(0)
            # The fragment came from HubSpot's heading ids, which no longer
            # exist; the page itself is the closest honest destination.
            return f']({target})'

        text, n_links = LEGACY.subn(swap, original)
        text, n_toc = TOC_BLOCK.subn(drop_toc, text)
        text = re.sub(r'\n{3,}', '\n\n', text)

        if text == original:
            continue
        files += 1
        relinked += n_links
        tocs += n_toc
        print(f'{path.relative_to(DOCS)}: {n_links} links, {n_toc} jump-link blocks')
        if apply:
            path.write_text(text)

    verb = 'fixed' if apply else 'would fix'
    print(f'\n{verb} {relinked} legacy links and {tocs} jump-link blocks '
          f'across {files} files' + (f'; {unmapped} unmapped' if unmapped else ''))


if __name__ == '__main__':
    main()
